permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Diet Water"
  description: |
    Diet Water is a website dedicated to selling an all natural diet supplement.

  rationales:
    typeface.primary: | Helvetica is the primary type face. 
