title: "Header"
description: |
    This is the header menu. It should be used at the top of the page and is for ordering.

patterns:
    header:
      title: "Header Navigation"
      description: |
      This navigation is at the top of the page and allows users to navigate orders.
      width: "20em"
      height: 400
