title: "Navigation"
description: |
    This is the navigation menu. It should be used at the top of the page.

patterns:
    header:
      title: "Header Navigation"
      description: |
      This navigation is at the top of the page and allows users to navigate the website to other pages.
      width: "20em"
      height: 400
